version: '3.8'
services:
  app:
    image: aoirint/rssensorconnector
    build: .
    restart: always
    devices:
      - /dev/ttyACM0:/dev/ttyArduino
      # - /dev/ttyUSB0:/dev/ttyArduino
    environment:
      TIMEZONE: Asia/Tokyo
      PYTHONUNBUFFERED: 1
      SERIAL_PORT: /dev/ttyArduino
      SERIAL_BAUDRATE: 38400
      DEBUG: 0

      POST_WEB: 1
      WEB_API_ENDPOINT: https://example.com/api/sensor
      WEB_API_TOKEN_ENDPOINT: https://example.com/api/token
      WEB_AUTH_USER: user
      WEB_AUTH_PASSWORD: password

      POST_TEAMS: 1
      TEAMS_INCOMING_WEBHOOK_URL: https://outlook.office.com/webhook/.../IncomingWebhook/.../...
      POST_INTERVAL: 300
      DOOR_POST_INTERVAL: 5

      POST_FIREBASE: 1
      FIREBASE_CREDENTIAL_PATH: firebase-credential.json
