version: '3'
services:
  app:
    build: .
    command: python SensorConnector.py
    restart: always
    volumes:
      - .:/code
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      # - /dev/ttyUSB0:/dev/ttyUSB0
    env_file:
      - .env
